// AUTO-GENERATED — DO NOT EDIT BY HAND.
// Source: fe/src/generated/permissions-catalog.json
// Regenerate: npm run permissions:generate-keys (or just rebuild)

/**
 * @description Type-safe map of every permission key registered in the BE catalog.
 * Use with useHasPermission(PERMISSION_KEYS.X) — never bare strings (per root CLAUDE.md).
 */
export const PERMISSION_KEYS = {
  AGENTS_CREATE: 'agents.create',
  AGENTS_CREDENTIALS: 'agents.credentials',
  AGENTS_DEBUG: 'agents.debug',
  AGENTS_DELETE: 'agents.delete',
  AGENTS_EDIT: 'agents.edit',
  AGENTS_EMBED: 'agents.embed',
  AGENTS_RUN: 'agents.run',
  AGENTS_VIEW: 'agents.view',
  API_KEYS_CREATE: 'api_keys.create',
  API_KEYS_DELETE: 'api_keys.delete',
  API_KEYS_EDIT: 'api_keys.edit',
  API_KEYS_VIEW: 'api_keys.view',
  AUDIT_EXPORT: 'audit.export',
  AUDIT_VIEW: 'audit.view',
  BROADCAST_CREATE: 'broadcast.create',
  BROADCAST_DELETE: 'broadcast.delete',
  BROADCAST_EDIT: 'broadcast.edit',
  BROADCAST_VIEW: 'broadcast.view',
  CHAT_API: 'chat.api',
  CHAT_CREATE: 'chat.create',
  CHAT_DELETE: 'chat.delete',
  CHAT_EDIT: 'chat.edit',
  CHAT_EMBED: 'chat.embed',
  CHAT_UPLOAD: 'chat.upload',
  CHAT_VIEW: 'chat.view',
  CHUNKS_CREATE: 'chunks.create',
  CHUNKS_DELETE: 'chunks.delete',
  CHUNKS_EDIT: 'chunks.edit',
  CHUNKS_VIEW: 'chunks.view',
  CODE_GRAPH_MANAGE: 'code_graph.manage',
  CODE_GRAPH_VIEW: 'code_graph.view',
  DASHBOARD_ADMIN: 'dashboard.admin',
  DASHBOARD_VIEW: 'dashboard.view',
  DATASETS_ADVANCED: 'datasets.advanced',
  DATASETS_CREATE: 'datasets.create',
  DATASETS_DELETE: 'datasets.delete',
  DATASETS_EDIT: 'datasets.edit',
  DATASETS_REINDEX: 'datasets.reindex',
  DATASETS_SHARE: 'datasets.share',
  DATASETS_VIEW: 'datasets.view',
  DOCUMENTS_BULK: 'documents.bulk',
  DOCUMENTS_CREATE: 'documents.create',
  DOCUMENTS_DELETE: 'documents.delete',
  DOCUMENTS_EDIT: 'documents.edit',
  DOCUMENTS_ENRICH: 'documents.enrich',
  DOCUMENTS_PARSE: 'documents.parse',
  DOCUMENTS_VIEW: 'documents.view',
  DOCUMENT_CATEGORIES_CREATE: 'document_categories.create',
  DOCUMENT_CATEGORIES_DELETE: 'document_categories.delete',
  DOCUMENT_CATEGORIES_EDIT: 'document_categories.edit',
  DOCUMENT_CATEGORIES_IMPORT: 'document_categories.import',
  DOCUMENT_CATEGORIES_VIEW: 'document_categories.view',
  FEEDBACK_DELETE: 'feedback.delete',
  FEEDBACK_EDIT: 'feedback.edit',
  FEEDBACK_SUBMIT: 'feedback.submit',
  FEEDBACK_VIEW: 'feedback.view',
  GLOSSARY_CREATE: 'glossary.create',
  GLOSSARY_DELETE: 'glossary.delete',
  GLOSSARY_EDIT: 'glossary.edit',
  GLOSSARY_IMPORT: 'glossary.import',
  GLOSSARY_VIEW: 'glossary.view',
  KNOWLEDGE_BASE_CHATS: 'knowledge_base.chats',
  KNOWLEDGE_BASE_CREATE: 'knowledge_base.create',
  KNOWLEDGE_BASE_DELETE: 'knowledge_base.delete',
  KNOWLEDGE_BASE_EDIT: 'knowledge_base.edit',
  KNOWLEDGE_BASE_SEARCHES: 'knowledge_base.searches',
  KNOWLEDGE_BASE_SHARE: 'knowledge_base.share',
  KNOWLEDGE_BASE_SYNC: 'knowledge_base.sync',
  KNOWLEDGE_BASE_VIEW: 'knowledge_base.view',
  LLM_PROVIDERS_CREATE: 'llm_providers.create',
  LLM_PROVIDERS_DELETE: 'llm_providers.delete',
  LLM_PROVIDERS_EDIT: 'llm_providers.edit',
  LLM_PROVIDERS_TEST: 'llm_providers.test',
  LLM_PROVIDERS_VIEW: 'llm_providers.view',
  MEMORY_CREATE: 'memory.create',
  MEMORY_DELETE: 'memory.delete',
  MEMORY_EDIT: 'memory.edit',
  MEMORY_VIEW: 'memory.view',
  PERMISSIONS_MANAGE: 'permissions.manage',
  PERMISSIONS_VIEW: 'permissions.view',
  PREVIEW_VIEW: 'preview.view',
  SEARCH_APPS_API: 'search_apps.api',
  SEARCH_APPS_CREATE: 'search_apps.create',
  SEARCH_APPS_DELETE: 'search_apps.delete',
  SEARCH_APPS_EDIT: 'search_apps.edit',
  SEARCH_APPS_EMBED: 'search_apps.embed',
  SEARCH_APPS_VIEW: 'search_apps.view',
  SYNC_CONNECTORS_CREATE: 'sync_connectors.create',
  SYNC_CONNECTORS_DELETE: 'sync_connectors.delete',
  SYNC_CONNECTORS_EDIT: 'sync_connectors.edit',
  SYNC_CONNECTORS_RUN: 'sync_connectors.run',
  SYNC_CONNECTORS_VIEW: 'sync_connectors.view',
  SYSTEM_HISTORY_VIEW: 'system_history.view',
  SYSTEM_PARSING_CONFIG: 'system.parsing_config',
  SYSTEM_TOOLS_RUN: 'system_tools.run',
  SYSTEM_TOOLS_VIEW: 'system_tools.view',
  SYSTEM_VIEW: 'system.view',
  TEAMS_CREATE: 'teams.create',
  TEAMS_DELETE: 'teams.delete',
  TEAMS_EDIT: 'teams.edit',
  TEAMS_MEMBERS: 'teams.members',
  TEAMS_PERMISSIONS: 'teams.permissions',
  TEAMS_VIEW: 'teams.view',
  USERS_ASSIGN_PERMS: 'users.assign_perms',
  USERS_ASSIGN_ROLE: 'users.assign_role',
  USERS_CREATE: 'users.create',
  USERS_DELETE: 'users.delete',
  USERS_EDIT: 'users.edit',
  USERS_VIEW: 'users.view',
  USERS_VIEW_IP: 'users.view_ip',
  USERS_VIEW_SESSIONS: 'users.view_sessions',
  USER_HISTORY_VIEW: 'user_history.view',
} as const

/** @description Union type of all valid permission keys from the catalog snapshot. */
export type PermissionKey = (typeof PERMISSION_KEYS)[keyof typeof PERMISSION_KEYS]
