/**
 * @fileoverview Public API barrel for projects feature.
 */
export {
  getProjects,
  getProjectById,
  createProject,
  updateProject,
  deleteProject,
  getProjectPermissions,
  setProjectPermission,
  removeProjectPermission,
  getDocumentCategories,
  createDocumentCategory,
  updateDocumentCategory,
  deleteDocumentCategory,
  getCategoryVersions,
  createCategoryVersion,
  syncCategoryVersion,
  archiveCategoryVersion,
  deleteCategoryVersion,
  getVersionDocuments,
  uploadVersionDocument,
  getProjectChats,
  getProjectChatById,
  createProjectChat,
  updateProjectChat,
  deleteProjectChat,
  syncProjectChat,
  getProjectSearches,
  getProjectSearchById,
  createProjectSearch,
  updateProjectSearch,
  deleteProjectSearch,
  syncProjectSearch,
  getSyncConfigs,
  createSyncConfig,
  updateSyncConfig,
  deleteSyncConfig,
  testSyncConnection,
  triggerSync,
  getProjectDatasets,
  linkProjectDataset,
  unlinkProjectDataset,
  type Project,
  type ProjectPermission,
  type DocumentCategory,
  type DocumentCategoryVersion,
  type ProjectChat,
  type ProjectSearch,
  type ProjectCategory,
  type ProjectDataset,
  type ProjectSyncConfig,
  type SyncSourceType,
} from "./api/projectService";

export {
  createDataset,
  listDatasets,
  updateDataset,
  deleteDatasets,
  type Dataset,
  type CreateDatasetParams,
  type UpdateDatasetParams,
  type ListDatasetsParams,
} from "./api/ragflowService";
